#db.url=${DB_URL}
#db.username=${DB_USERNAME}
#db.password=${DB_PASSWORD}
#db.driverClassName=org.postgresql.Driver

db.url=jdbc:postgresql://localhost:5433/employee_payroll_db
db.username=postgres
db.password=Radhika@2005
db.driverClassName=org.postgresql.Driver